//
//  VisionBreedList.swift
//  Resque
//
//  Created by Roback, Jerry on 1/24/18.
//  Copyright © 2018 Roback, Jerry. All rights reserved.
//

import Foundation







var visionBreedList = [
"Affenpinscher, Monkey Pinscher, Monkey Dog",
"Afghan Hound, Afghan",
"Airedale, Airedale Terrier",
"Akbash",
"Akita",
"Malamute, Malemute, Alaskan Malamute",
"American Bulldog",
"Eskimo Dog, Husky",
"Mexican Hairless",
"American Staffordshire Terrier, Staffordshire Terrier, American Pit Bull Terrier, Pit Bull Terrier",
"American Water Spaniel",
"Anatolian Shepherd",
"Appenzeller",
"Blue Heeler",
"Kelpie",
"Australian Shepherd",
"Australian Terrier",
"Basenji",
"Basset, Basset Hound",
"Beagle",
"Bearded Collie",
"Beauceron",
"Bedlington Terrier",
"Groenendael",
"Belgian Shepherd Laekenois",
"Malinois",
"Tervuren",
"Bernese Mountain Dog",
"Toy Poodle",
"Black-And-Tan Coonhound",
"Black Labrador Retriever",
"Black Mouth Cur",
"Black Russian Terrier",
"Bloodhound, Sleuthhound",
"Blue Lacy",
"Bluetick",
"Boerboel",
"Bolognese",
"Border Collie",
"Border Terrier",
"Borzoi, Russian Wolfhound",
"Boston Bull, Boston Terrier",
"Bouvier Des Flandres, Bouviers Des Flandres",
"Boxer",
"Boykin Spaniel",
"Briard",
"Brittany Spaniel",
"Brabancon Griffon",
"Staffordshire Bullterrier, Staffordshire Bull Terrier",
"Bull Mastiff",
"Cairn, Cairn Terrier",
"Dingo, Warrigal, Warragal, Canis Dingo",
"Cane Corso Mastiff",
"Carolina Dog",
"Catahoula Leopard Dog",
"Cattle Dog",
"Leonberg",
"Blenheim Spaniel",
"Chesapeake Bay Retriever",
"Chihuahua",
"Chinese Crested Dog",
"Chinese Foo Dog",
"Chinook",
"Chocolate Labrador Retriever",
"Chow, Chow Chow",
"Ibizan Hound, Ibizan Podenco",
"Clumber, Clumber Spaniel",
"Cockapoo",
"Cocker Spaniel, English Cocker Spaniel, Cocker",
"Collie",
"Coonhound",
"Cardigan, Cardigan Welsh Corgi",
"Coton de Tulear",
"Curly-Coated Retriever",
"Dachshund",
"Dalmatian, Coach Dog, Carriage Dog",
"Dandie Dinmont, Dandie Dinmont Terrier",
"Doberman, Doberman Pinscher",
"Dogo Argentino",
"Dogue de Bordeaux",
"Dutch Shepherd",
"English Bulldog",
"English Cocker Spaniel",
"English Coonhound",
"German Short-haired Pointer",
"English Setter",
"English Shepherd",
"English Springer, English Springer Spaniel",
"English Toy Spaniel",
"EntleBucher",
"Samoyed, Samoyede",
"Feist",
"Field Spaniel",
"Fila Brasileiro",
"Finnish Lapphund",
"Finnish Spitz",
"Flat-Coated Retriever",
"Fox Terrier",
"English Foxhound",
"French Bulldog",
"Galgo Spanish Greyhound",
"German Pinscher",
"German Shepherd, German Shepherd Dog, German Police Dog, Alsatian",
"German Short-Haired Pointer",
"German Spitz",
"German Wirehaired Pointer",
"Giant Schnauzer",
"Glen of Imaal Terrier",
"Golden Retriever",
"Gordon Setter",
"Great Dane",
"Great Pyrenees",
"Greater Swiss Mountain Dog",
"Greyhound",
"Walker Hound, Walker Foxhound",
"Havanese",
"Hound",
"Hovawart",
"Husky",
"Ibizan Hound, Ibizan Podenco",
"Illyrian Sheepdog",
"Irish Setter, Red Setter",
"Irish Terrier",
"Irish Water Spaniel",
"Irish Wolfhound",
"Italian Greyhound",
"Italian Spinone",
"Jack Russell Terrier",
"Jack Russell Terrier (Parson Russell Terrier)",
"Japanese Spaniel",
"Jindo",
"Kai Dog",
"Karelian Bear Dog",
"Keeshond",
"Kerry Blue Terrier",
"Kishu",
"Klee Kai",
"Komondor",
"Kuvasz",
"Kyi Leo",
"Labrador Retriever",
"Lakeland Terrier",
"Lancashire Heeler",
"Leonberg",
"Lhasa, Lhasa Apso",
"Lowchen",
"Maltese Dog, Maltese Terrier, Maltese",
"Manchester Terrier",
"Maremma Sheepdog",
"Mastiff",
"McNab",
"Miniature Pinscher",
"Mountain Cur",
"Mountain Dog",
"Munsterlander",
"Neapolitan Mastiff",
"New Guinea Singing Dog",
"Newfoundland, Newfoundland Dog",
"Norfolk Terrier",
"Norwegian Buhund",
"Norwegian Elkhound, Elkhound",
"Norwegian Lundehund",
"Norwich Terrier",
"Nova Scotia Duck-Tolling Retriever",
"Old English Sheepdog, Bobtail",
"Otterhound, Otter Hound",
"Papillon",
"Patterdale Terrier (Fell Terrier)",
"Pekinese, Pekingese, Peke",
"Peruvian Inca Orchid",
"Petit Basset Griffon Vendeen",
"Pharaoh Hound",
"Pit Bull Terrier",
"Plott Hound",
"Podengo Portugueso",
"Pointer",
"Polish Lowland Sheepdog",
"Pomeranian",
"Miniature Poodle",
"Portuguese Water Dog",
"Presa Canario",
"Pug, Pug-Dog",
"Puli",
"Pumi",
"Rat Terrier",
"Redbone",
"Retriever",
"Rhodesian Ridgeback",
"Rottweiler",
"Saint Bernard, St Bernard",
"Saluki, Gazelle Hound",
"Samoyed, Samoyede",
"Sarplaninac",
"Schipperke",
"Standard Schnauzer",
"Scottish Deerhound, Deerhound",
"Scotch Terrier, Scottish Terrier, Scottie",
"Sealyham Terrier, Sealyham",
"Setter",
"Shar Pei",
"Sheep Dog",
"Shepherd",
"Shetland Sheepdog, Shetland Sheep Dog, Shetland",
"Shiba Inu",
"Shih-Tzu",
"Siberian Husky",
"Silky Terrier, Sydney Silky",
"Skye Terrier",
"Sloughi",
"Smooth Fox Terrier",
"South Russian Ovtcharka",
"Spaniel",
"Spitz",
"Staffordshire Bull Terrier",
"Standard Poodle",
"Sussex Spaniel",
"Swedish Vallhund",
"Terrier",
"Thai Ridgeback",
"Tibetan Mastiff",
"Tibetan Spaniel",
"Tibetan Terrier, Chrysanthemum Dog",
"Tosa Inu",
"Toy Terrier",
"Treeing Walker Coonhound",
"Vizsla, Hungarian Pointer",
"Weimaraner",
"Pembroke, Pembroke Welsh Corgi",
"Welsh Springer Spaniel",
"Welsh Terrier",
"West Highland White Terrier",
"Soft-Coated Wheaten Terrier",
"Whippet",
"White German Shepherd",
"Wire-Haired Fox Terrier",
"Wire-Haired Pointing Griffon",
"Wirehaired Terrier",
"Mexican Hairless",
"Yellow Labrador Retriever",
"Yorkshire Terrier"
]
